version: '2'
services:
  gatsby:
    image: debian
    build: "./src"
    ports:
      - "8000:8000"
    volumes:
      - "./src:/var/app"
      - "./data:/var/data"
#    entrypoint: cd /var/app/gatsby-starter-redi-school/ && /usr/bin/gatsby develop

